In [1]:
#!c1.8
import pandas as pd
import os
import numpy as np
import pickle
from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error
from catboost import CatBoostRegressor

In [19]:
pd.read_csv("7.csv").rename({
    "Дата и время": "datetime",
    "CO": "co",
    "NO2": "no2",
    "NO": "no",
    "PM10": "pm10",
    "PM2.5": "pm25",
    "-T-": "temperature",
    "| V |": "wind_speed",
    "_V_": "wind_direction",
    "Давление": "pressure",
    "Влажность": "humidity",
    "Осадки": "precipitation"
}, axis=1)

,datetime,co,no2,no,pm25,pressure,humidity,wind_speed,wind_direction,temperature,precipitation
0,07.04.2021 00:00,0.5,0.0483,0.002,0.016,736.6,69.1,0.0,0.0,6.5,0.0
1,07.04.2021 00:20,0.4,0.0454,0.002,0.016,736.5,69.0,0.0,0.0,6.5,0.0
2,07.04.2021 00:40,0.4,0.0429,0.001,0.015,736.4,69.4,0.0,0.0,6.6,0.0
3,07.04.2021 01:00,0.4,0.0464,0.002,0.016,736.5,70.1,0.6,335.0,6.5,0.0
4,07.04.2021 01:20,0.3,0.0313,0.000,0.015,736.6,70.4,1.2,0.0,6.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...
1867,27.07.2021 22:20,NaN,NaN,NaN,NaN,746.9,63.0,0.0,0.0,20.8,0.0
1868,27.07.2021 22:40,NaN,NaN,NaN,NaN,746.9,62.9,0.3,324.0,21.0,0.0
1869,27.07.2021 23:00,NaN,NaN,NaN,NaN,746.9,56.1,0.4,0.0,22.6,0.0
1870,27.07.2021 23:20,NaN,NaN,NaN,NaN,746.9,60.2,0.0,0.0,21.3,0.0
1871,27.07.2021 23:40,NaN,NaN,NaN,NaN,747.0,63.4,0.0,0.0,20.7,0.0

In [2]:
#!c1.8
pd.set_option("display.max_columns", None)

In [4]:
#!c1.8
data = pd.read_csv("Останкино/Ostankino_6years_data.csv")

In [5]:
#!c1.8
data.head()

,Дата и время,CO,NO2,NO,PM10,-T-,| V |,_V_,Давление,Влажность,Осадки
0,01/01/2015 00:00,0.2,0.01,0.0,0.01,-6.4,1.1,0.0,743.8,72.0,0.0
1,01/01/2015 00:20,0.2,0.01,0.0,0.01,-6.3,1.7,0.0,743.7,72.0,0.0
2,01/01/2015 00:40,0.2,0.01,0.0,0.01,-6.2,1.3,0.0,743.6,72.0,0.0
3,01/01/2015 01:00,0.2,0.01,0.0,0.01,-6.1,1.6,176.0,743.5,72.0,0.0
4,01/01/2015 01:20,0.3,0.01,0.0,0.02,-6.0,1.0,171.0,743.5,72.0,0.0

In [6]:
#!c1.8
with open("ostankino_6years_meteoprofile", "rb") as f:
    daily_tables = pickle.load(f)
ost_profile_data = pd.concat(daily_tables)

In [22]:
#!c1.8
for i in range(ost_prost_profile_dataa.shape[0]):
    try:
        pd.to_datetime(ost_profile_data.iat[i, 0])
    except BaseException:
        print(ost_profile_data.iat[i, 0])

0
0
0
0
0
0
0
0
0
0
0
0
0
0
03/08/2020 00:20:00

In [26]:
#!c1.8
pd.to_datetime("03/08/2020 00:20:00", format="%d/%m/%Y %H:%M:%S")

Timestamp('2020-08-03 00:20:00')

In [24]:
#!c1.8
ost_profile_data.loc[ost_profile_data["data time"] != '0']

             data time   0  50  100  150  200  250  300  350  400  450  500  \
20171208 10          0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         92          0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         106         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         108         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         110         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         112         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         114         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         116         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         118         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         120         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         122         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         124         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         126         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
         128         0 NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

              550  600  OutsideTemperature
20171208 10   NaN  NaN                 NaN
         92   NaN  NaN                 NaN
         106  NaN  NaN                 NaN
         108  NaN  NaN                 NaN
         110  NaN  NaN                 NaN
         112  NaN  NaN                 NaN
         114  NaN  NaN                 NaN
         116  NaN  NaN                 NaN
         118  NaN  NaN                 NaN
         120  NaN  NaN                 NaN
         122  NaN  NaN                 NaN
         124  NaN  NaN                 NaN
         126  NaN  NaN                 NaN
         128  NaN  NaN                 NaN

In [7]:
#!c1.8
ost_profile_data = ost_profile_data.loc[ost_profile_data["data time"] != '0']
ost_profile_data["data time"] = pd.to_datetime(ost_profile_data["data time"], format="%d/%m/%Y %H:%M:%S")
ost_profile_data.rename({
    "data time": "datetime",
    "0": "t_0m",
    "50": "t_50m",
    "100": "t_100m",
    "150": "t_150m",
    "200": "t_200m",
    "250": "t_250m",
    "300": "t_300m",
    "350": "t_350m",
    "400": "t_400m",
    "450": "t_450m",
    "500": "t_500m",
    "550": "t_550m",
    "600": "t_600m",
    "OutsideTemperature": "outside_temperature"
}, axis=1, inplace =True)
ost_profile_data.reset_index(drop=True, inplace=True)
ost_profile_data = ost_profile_data.resample("20min", on="datetime").mean().reset_index()

In [8]:
#!c1.8
ost_profile_data["outside_temperature"] = ost_profile_data["t_0m"]
ost_profile_data["253_wind_direction"] = np.nan
ost_profile_data["253_wind_speed"] = np.nan

In [34]:
#!c1.8
ost_profile_data.head(20)

,datetime,t_0m,t_50m,t_100m,t_150m,t_200m,t_250m,t_300m,t_350m,t_400m,t_450m,t_500m,t_550m,t_600m,outside_temperature,253_wind_direction,253_wind_speed
0,2015-01-01 00:00:00,-6.7200,-7.3300,-7.9150,-8.4475,-8.7850,-8.9425,-8.9100,-8.7500,-8.4975,-8.2575,-8.0475,-7.7975,-7.5475,-6.7200,NaN,NaN
1,2015-01-01 00:20:00,-6.5725,-7.2400,-7.8600,-8.2750,-8.4350,-8.5525,-8.5250,-8.3300,-8.0300,-7.7675,-7.5600,-7.3325,-7.1075,-6.5725,NaN,NaN
2,2015-01-01 00:40:00,-6.4100,-7.1000,-7.6800,-8.0700,-8.3025,-8.3425,-8.1700,-7.9225,-7.6450,-7.4025,-7.1975,-6.9625,-6.7250,-6.4100,NaN,NaN
3,2015-01-01 01:00:00,-6.3400,-6.9725,-7.5725,-7.9900,-8.2225,-8.2350,-8.0450,-7.7625,-7.4550,-7.1875,-6.9625,-6.7100,-6.4600,-6.3400,NaN,NaN
4,2015-01-01 01:20:00,-6.2675,-6.8625,-7.4300,-7.8525,-8.0925,-8.0425,-7.8050,-7.4750,-7.1450,-6.8650,-6.6175,-6.3425,-6.0650,-6.2675,NaN,NaN
5,2015-01-01 01:40:00,-6.1400,-6.8525,-7.4025,-7.7950,-7.9300,-7.9025,-7.6925,-7.3875,-7.0575,-6.7875,-6.5600,-6.3125,-6.0600,-6.1400,NaN,NaN
6,2015-01-01 02:00:00,-6.0600,-6.7475,-7.3225,-7.6775,-7.8100,-7.7400,-7.4700,-7.1225,-6.7850,-6.5100,-6.2800,-6.0325,-5.7850,-6.0600,NaN,NaN
7,2015-01-01 02:20:00,-5.9275,-6.5600,-7.1000,-7.4700,-7.6575,-7.5775,-7.3300,-7.0000,-6.6750,-6.4075,-6.1750,-5.9200,-5.6650,-5.9275,NaN,NaN
8,2015-01-01 02:40:00,-5.7875,-6.4350,-6.8825,-7.1700,-7.2725,-7.2300,-7.0200,-6.7600,-6.4900,-6.2750,-6.1050,-5.9175,-5.7300,-5.7875,NaN,NaN
9,2015-01-01 03:00:00,-5.7000,-6.2900,-6.8125,-7.1075,-7.2400,-7.1600,-6.9100,-6.5750,-6.2450,-5.9825,-5.7575,-5.5175,-5.2725,-5.7000,NaN,NaN
10,2015-01-01 03:20:00,-5.5175,-6.1050,-6.5925,-6.8475,-6.9575,-6.9275,-6.7225,-6.4550,-6.1725,-5.9575,-5.7850,-5.6050,-5.4175,-5.5175,NaN,NaN
11,2015-01-01 03:40:00,-5.3775,-5.8875,-6.3075,-6.5925,-6.7450,-6.7025,-6.4950,-6.2200,-5.9475,-5.7300,-5.5425,-5.3325,-5.1200,-5.3775,NaN,NaN
12,2015-01-01 04:00:00,-5.1375,-5.6325,-6.0625,-6.3350,-6.4425,-6.3700,-6.1725,-5.8900,-5.5900,-5.3625,-5.1750,-4.9700,-4.7625,-5.1375,NaN,NaN
13,2015-01-01 04:20:00,-4.9350,-5.3950,-5.8175,-6.1200,-6.2700,-6.2100,-6.0200,-5.7375,-5.4425,-5.2175,-5.0225,-4.8050,-4.5850,-4.9350,NaN,NaN
14,2015-01-01 04:40:00,-4.7000,-5.1375,-5.5150,-5.7700,-5.8000,-5.7275,-5.5600,-5.2825,-4.9775,-4.7550,-4.5750,-4.3775,-4.1900,-4.7000,NaN,NaN
15,2015-01-01 05:00:00,-4.4900,-4.8925,-5.3700,-5.5350,-5.5825,-5.5300,-5.3375,-5.0575,-4.7650,-4.5675,-4.4250,-4.2950,-4.1600,-4.4900,NaN,NaN
16,2015-01-01 05:20:00,-4.2900,-4.6900,-5.0800,-5.2925,-5.3950,-5.4150,-5.2850,-5.0750,-4.8425,-4.6875,-4.5625,-4.4275,-4.2950,-4.2900,NaN,NaN
17,2015-01-01 05:40:00,-4.1575,-4.5275,-4.9175,-5.1025,-5.2675,-5.3175,-5.2550,-5.1075,-4.9150,-4.7825,-4.6850,-4.5750,-4.4650,-4.1575,NaN,NaN
18,2015-01-01 06:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,2015-01-01 06:20:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#!c1.8
# Drop empty cols, rename then, cast datetime to datetime, join with city-level Ostankino data
data = data.loc[:, [name for name in data.columns if "Unnamed" not in name]]
data.dropna(axis=1, how="all", inplace=True)
data.rename({
    "Дата и время": "datetime",
    "CO": "co",
    "NO2": "no2",
    "NO": "no",
    "PM10": "pm10",
    "PM2.5": "pm25",
    "-T-": "temperature",
    "| V |": "wind_speed",
    "_V_": "wind_direction",
    "Давление": "pressure",
    "Влажность": "humidity",
    "Осадки": "precipitation"
}, axis=1, inplace=True)
data["datetime"] = pd.to_datetime(data["datetime"],  format="%d/%m/%Y %H:%M")
data = pd.merge(data, ost_profile_data, how="inner", on="datetime")

In [42]:
#!c1.8
data.dtypes

datetime               datetime64[ns]
co                            float64
no2                           float64
no                            float64
pm10                          float64
temperature                   float64
wind_speed                    float64
wind_direction                float64
pressure                      float64
humidity                      float64
precipitation                 float64
t_0m                          float64
t_50m                         float64
t_100m                        float64
t_150m                        float64
t_200m                        float64
t_250m                        float64
t_300m                        float64
t_350m                        float64
t_400m                        float64
t_450m                        float64
t_500m                        float64
t_550m                        float64
t_600m                        float64
outside_temperature           float64
253_wind_direction            float64
253_wind_speed                float64
dtype: object

In [10]:
#!c1.8

# Split by pollutant
pollutants = ["co", "no2", "no", "pm10", "pm25"]
data_parts = {}
for p in pollutants:
    if p in data.columns:
        cols_to_keep = ["temperature", "wind_speed", "wind_direction",\
                        "pressure", "humidity", "precipitation"] + [p] + list(ost_profile_data.columns)
        data_part = data.loc[:, cols_to_keep]
        data_part.rename({p: "pollutant_concentration"}, axis=1,inplace=True)
        data_part = data_part.loc[data_part["pollutant_concentration"] > 0.0]
        data_parts[p] = data_part

In [11]:
#!c1.8
# Add separate date and time variables
for pollutant, table in data_parts.items():
    table["month"] = table["datetime"].dt.month
    table["day"] = table["datetime"].dt.day
    table["day_of_week"] = table["datetime"].dt.weekday
    table["hour"] = table["datetime"].dt.hour
    table.index = pd.Index(table.datetime)
    table.drop("datetime", axis=1, inplace=True)
data_parts[pollutant] = table

In [12]:
#!c1.8
    
# Generate historical features
# Use rolling to capture some previuos and next measures
hist_features = ["temperature", "wind_speed", "wind_direction",\
                            "pressure", "humidity", "precipitation", "pollutant_concentration"]
for pollutant, table in data_parts.items():
    for timeshift in [*range(1, 25)] + [168]:
        for feature in hist_features:
            if feature not in list(table.columns):
                continue
            col_name = feature + "_prev_" + str(timeshift) + "h"
            if timeshift == 168:
                window = 9
            else:
                window_size = 6
            col_value = table[feature].rolling(window=window_size).mean().shift(3*timeshift)
            table[col_name] = col_value
    data_parts[pollutant] = table

# Generate forecast features
forecast_features = ["temperature", "wind_speed", "wind_direction",\
                        "pressure", "humidity", "precipitation"]
for pollutant, table in data_parts.items():
    for timeshift in range(1, 25):
        for feature in forecast_features:
            col_name = feature + "_forecast_" + str(timeshift) + "h"
            col_value = table[feature].rolling(window=6).mean().shift(-3*timeshift)
            table[col_name] = col_value
    data_parts[pollutant] = table

# Generate target [pollution in 1…24 hours]
for pollutant, table in data_parts.items():
    for timeshift in range(1, 25):
        col_name = "target_" + str(timeshift) + "h"
        col_value = table["pollutant_concentration"].shift(-3*timeshift)
        table[col_name] = col_value
    data_parts[pollutant] = table

In [14]:
#!c1.8
list(data_parts["no2"].columns)

['temperature',
 'wind_speed',
 'wind_direction',
 'pressure',
 'humidity',
 'precipitation',
 'pollutant_concentration',
 't_0m',
 't_50m',
 't_100m',
 't_150m',
 't_200m',
 't_250m',
 't_300m',
 't_350m',
 't_400m',
 't_450m',
 't_500m',
 't_550m',
 't_600m',
 'outside_temperature',
 '253_wind_direction',
 '253_wind_speed',
 'month',
 'day',
 'day_of_week',
 'hour',
 'temperature_prev_1h',
 'wind_speed_prev_1h',
 'wind_direction_prev_1h',
 'pressure_prev_1h',
 'humidity_prev_1h',
 'precipitation_prev_1h',
 'pollutant_concentration_prev_1h',
 'temperature_prev_2h',
 'wind_speed_prev_2h',
 'wind_direction_prev_2h',
 'pressure_prev_2h',
 'humidity_prev_2h',
 'precipitation_prev_2h',
 'pollutant_concentration_prev_2h',
 'temperature_prev_3h',
 'wind_speed_prev_3h',
 'wind_direction_prev_3h',
 'pressure_prev_3h',
 'humidity_prev_3h',
 'precipitation_prev_3h',
 'pollutant_concentration_prev_3h',
 'temperature_prev_4h',
 'wind_speed_prev_4h',
 'wind_direction_prev_4h',
 'pressure_prev_4h',
 'humidity_prev_4h',
 'precipitation_prev_4h',
 'pollutant_concentration_prev_4h',
 'temperature_prev_5h',
 'wind_speed_prev_5h',
 'wind_direction_prev_5h',
 'pressure_prev_5h',
 'humidity_prev_5h',
 'precipitation_prev_5h',
 'pollutant_concentration_prev_5h',
 'temperature_prev_6h',
 'wind_speed_prev_6h',
 'wind_direction_prev_6h',
 'pressure_prev_6h',
 'humidity_prev_6h',
 'precipitation_prev_6h',
 'pollutant_concentration_prev_6h',
 'temperature_prev_7h',
 'wind_speed_prev_7h',
 'wind_direction_prev_7h',
 'pressure_prev_7h',
 'humidity_prev_7h',
 'precipitation_prev_7h',
 'pollutant_concentration_prev_7h',
 'temperature_prev_8h',
 'wind_speed_prev_8h',
 'wind_direction_prev_8h',
 'pressure_prev_8h',
 'humidity_prev_8h',
 'precipitation_prev_8h',
 'pollutant_concentration_prev_8h',
 'temperature_prev_9h',
 'wind_speed_prev_9h',
 'wind_direction_prev_9h',
 'pressure_prev_9h',
 'humidity_prev_9h',
 'precipitation_prev_9h',
 'pollutant_concentration_prev_9h',
 'temperature_prev_10h',
 'wind_speed_prev_10h',
 'wind_direction_prev_10h',
 'pressure_prev_10h',
 'humidity_prev_10h',
 'precipitation_prev_10h',
 'pollutant_concentration_prev_10h',
 'temperature_prev_11h',
 'wind_speed_prev_11h',
 'wind_direction_prev_11h',
 'pressure_prev_11h',
 'humidity_prev_11h',
 'precipitation_prev_11h',
 'pollutant_concentration_prev_11h',
 'temperature_prev_12h',
 'wind_speed_prev_12h',
 'wind_direction_prev_12h',
 'pressure_prev_12h',
 'humidity_prev_12h',
 'precipitation_prev_12h',
 'pollutant_concentration_prev_12h',
 'temperature_prev_13h',
 'wind_speed_prev_13h',
 'wind_direction_prev_13h',
 'pressure_prev_13h',
 'humidity_prev_13h',
 'precipitation_prev_13h',
 'pollutant_concentration_prev_13h',
 'temperature_prev_14h',
 'wind_speed_prev_14h',
 'wind_direction_prev_14h',
 'pressure_prev_14h',
 'humidity_prev_14h',
 'precipitation_prev_14h',
 'pollutant_concentration_prev_14h',
 'temperature_prev_15h',
 'wind_speed_prev_15h',
 'wind_direction_prev_15h',
 'pressure_prev_15h',
 'humidity_prev_15h',
 'precipitation_prev_15h',
 'pollutant_concentration_prev_15h',
 'temperature_prev_16h',
 'wind_speed_prev_16h',
 'wind_direction_prev_16h',
 'pressure_prev_16h',
 'humidity_prev_16h',
 'precipitation_prev_16h',
 'pollutant_concentration_prev_16h',
 'temperature_prev_17h',
 'wind_speed_prev_17h',
 'wind_direction_prev_17h',
 'pressure_prev_17h',
 'humidity_prev_17h',
 'precipitation_prev_17h',
 'pollutant_concentration_prev_17h',
 'temperature_prev_18h',
 'wind_speed_prev_18h',
 'wind_direction_prev_18h',
 'pressure_prev_18h',
 'humidity_prev_18h',
 'precipitation_prev_18h',
 'pollutant_concentration_prev_18h',
 'temperature_prev_19h',
 'wind_speed_prev_19h',
 'wind_direction_prev_19h',
 'pressure_prev_19h',
 'humidity_prev_19h',
 'precipitation_prev_19h',
 'pollutant_concentration_prev_19h',
 'temperature_prev_20h',
 'wind_speed_prev_20h',
 'wind_direction_prev_20h',
 'pressure_prev_20h',
 'humidity_prev_20h',
 'precipitation_prev_20h',
 'pollutant_concentration_prev_20h',
 'temperature_prev_21h',
 'wind_speed_prev_21h',
 'wind_direction_prev_21h',
 'pressure_prev_21h',
 'humidity_prev_21h',
 'precipitation_prev_21h',
 'pollutant_concentration_prev_21h',
 'temperature_prev_22h',
 'wind_speed_prev_22h',
 'wind_direction_prev_22h',
 'pressure_prev_22h',
 'humidity_prev_22h',
 'precipitation_prev_22h',
 'pollutant_concentration_prev_22h',
 'temperature_prev_23h',
 'wind_speed_prev_23h',
 'wind_direction_prev_23h',
 'pressure_prev_23h',
 'humidity_prev_23h',
 'precipitation_prev_23h',
 'pollutant_concentration_prev_23h',
 'temperature_prev_24h',
 'wind_speed_prev_24h',
 'wind_direction_prev_24h',
 'pressure_prev_24h',
 'humidity_prev_24h',
 'precipitation_prev_24h',
 'pollutant_concentration_prev_24h',
 'temperature_prev_168h',
 'wind_speed_prev_168h',
 'wind_direction_prev_168h',
 'pressure_prev_168h',
 'humidity_prev_168h',
 'precipitation_prev_168h',
 'pollutant_concentration_prev_168h',
 'temperature_forecast_1h',
 'wind_speed_forecast_1h',
 'wind_direction_forecast_1h',
 'pressure_forecast_1h',
 'humidity_forecast_1h',
 'precipitation_forecast_1h',
 'temperature_forecast_2h',
 'wind_speed_forecast_2h',
 'wind_direction_forecast_2h',
 'pressure_forecast_2h',
 'humidity_forecast_2h',
 'precipitation_forecast_2h',
 'temperature_forecast_3h',
 'wind_speed_forecast_3h',
 'wind_direction_forecast_3h',
 'pressure_forecast_3h',
 'humidity_forecast_3h',
 'precipitation_forecast_3h',
 'temperature_forecast_4h',
 'wind_speed_forecast_4h',
 'wind_direction_forecast_4h',
 'pressure_forecast_4h',
 'humidity_forecast_4h',
 'precipitation_forecast_4h',
 'temperature_forecast_5h',
 'wind_speed_forecast_5h',
 'wind_direction_forecast_5h',
 'pressure_forecast_5h',
 'humidity_forecast_5h',
 'precipitation_forecast_5h',
 'temperature_forecast_6h',
 'wind_speed_forecast_6h',
 'wind_direction_forecast_6h',
 'pressure_forecast_6h',
 'humidity_forecast_6h',
 'precipitation_forecast_6h',
 'temperature_forecast_7h',
 'wind_speed_forecast_7h',
 'wind_direction_forecast_7h',
 'pressure_forecast_7h',
 'humidity_forecast_7h',
 'precipitation_forecast_7h',
 'temperature_forecast_8h',
 'wind_speed_forecast_8h',
 'wind_direction_forecast_8h',
 'pressure_forecast_8h',
 'humidity_forecast_8h',
 'precipitation_forecast_8h',
 'temperature_forecast_9h',
 'wind_speed_forecast_9h',
 'wind_direction_forecast_9h',
 'pressure_forecast_9h',
 'humidity_forecast_9h',
 'precipitation_forecast_9h',
 'temperature_forecast_10h',
 'wind_speed_forecast_10h',
 'wind_direction_forecast_10h',
 'pressure_forecast_10h',
 'humidity_forecast_10h',
 'precipitation_forecast_10h',
 'temperature_forecast_11h',
 'wind_speed_forecast_11h',
 'wind_direction_forecast_11h',
 'pressure_forecast_11h',
 'humidity_forecast_11h',
 'precipitation_forecast_11h',
 'temperature_forecast_12h',
 'wind_speed_forecast_12h',
 'wind_direction_forecast_12h',
 'pressure_forecast_12h',
 'humidity_forecast_12h',
 'precipitation_forecast_12h',
 'temperature_forecast_13h',
 'wind_speed_forecast_13h',
 'wind_direction_forecast_13h',
 'pressure_forecast_13h',
 'humidity_forecast_13h',
 'precipitation_forecast_13h',
 'temperature_forecast_14h',
 'wind_speed_forecast_14h',
 'wind_direction_forecast_14h',
 'pressure_forecast_14h',
 'humidity_forecast_14h',
 'precipitation_forecast_14h',
 'temperature_forecast_15h',
 'wind_speed_forecast_15h',
 'wind_direction_forecast_15h',
 'pressure_forecast_15h',
 'humidity_forecast_15h',
 'precipitation_forecast_15h',
 'temperature_forecast_16h',
 'wind_speed_forecast_16h',
 'wind_direction_forecast_16h',
 'pressure_forecast_16h',
 'humidity_forecast_16h',
 'precipitation_forecast_16h',
 'temperature_forecast_17h',
 'wind_speed_forecast_17h',
 'wind_direction_forecast_17h',
 'pressure_forecast_17h',
 'humidity_forecast_17h',
 'precipitation_forecast_17h',
 'temperature_forecast_18h',
 'wind_speed_forecast_18h',
 'wind_direction_forecast_18h',
 'pressure_forecast_18h',
 'humidity_forecast_18h',
 'precipitation_forecast_18h',
 'temperature_forecast_19h',
 'wind_speed_forecast_19h',
 'wind_direction_forecast_19h',
 'pressure_forecast_19h',
 'humidity_forecast_19h',
 'precipitation_forecast_19h',
 'temperature_forecast_20h',
 'wind_speed_forecast_20h',
 'wind_direction_forecast_20h',
 'pressure_forecast_20h',
 'humidity_forecast_20h',
 'precipitation_forecast_20h',
 'temperature_forecast_21h',
 'wind_speed_forecast_21h',
 'wind_direction_forecast_21h',
 'pressure_forecast_21h',
 'humidity_forecast_21h',
 'precipitation_forecast_21h',
 'temperature_forecast_22h',
 'wind_speed_forecast_22h',
 'wind_direction_forecast_22h',
 'pressure_forecast_22h',
 'humidity_forecast_22h',
 'precipitation_forecast_22h',
 'temperature_forecast_23h',
 'wind_speed_forecast_23h',
 'wind_direction_forecast_23h',
 'pressure_forecast_23h',
 'humidity_forecast_23h',
 'precipitation_forecast_23h',
 'temperature_forecast_24h',
 'wind_speed_forecast_24h',
 'wind_direction_forecast_24h',
 'pressure_forecast_24h',
 'humidity_forecast_24h',
 'precipitation_forecast_24h',
 'target_1h',
 'target_2h',
 'target_3h',
 'target_4h',
 'target_5h',
 'target_6h',
 'target_7h',
 'target_8h',
 'target_9h',
 'target_10h',
 'target_11h',
 'target_12h',
 'target_13h',
 'target_14h',
 'target_15h',
 'target_16h',
 'target_17h',
 'target_18h',
 'target_19h',
 'target_20h',
 'target_21h',
 'target_22h',
 'target_23h',
 'target_24h']

In [ ]:
#!c1.8
metrics_by_pollutant = {}
f_imp_by_pollutant = {}
station_number = 3

for pollutant_name, pollutant_data in data_parts.items():
    target_names = [name for name in pollutant_data.columns if "target" in name]
    train_data = pollutant_data.dropna(axis=0, subset=target_names)

    if train_data.shape[0] < 10000:
        print(f"Not enough data for {pollutant_name} on station {station_number}:\
        n of rows in the dataset is {train_data.shape}, skipping.")
        continue

    X = train_data.drop(target_names, axis=1)
    y = train_data.loc[:, target_names]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.2, random_state=33)

    catboost_params = {
        "iterations": 100,
        "verbose": 10,
        "learning_rate": 1,
        "depth": 8,
        "loss_function": "MultiRMSE"}
    model =  CatBoostRegressor(**catboost_params)
    model.fit(X_train, y_train)

    model.save_model(f"ostankino_6years_models/{station_number}_{pollutant_name}.cbm")

    predictions = model.predict(X_test)

    predictions[predictions < 0] = 0

    r2 = r2_score(y_test, predictions, multioutput="raw_values")
    mse = mean_squared_error(y_test, predictions, multioutput="raw_values")
    rmse = model.get_best_score()
    metrics_by_pollutant[pollutant_name] = pd.DataFrame({"r2": r2, "mse": mse, "rmse": rmse["learn"]["MultiRMSE"]})

    f_imp_by_pollutant[pollutant_name] = pd.DataFrame({"features": list(X.columns),
                                                       "importance": model.get_feature_importance()})
metrics = pd.concat(metrics_by_pollutant)
f_imp = pd.concat(f_imp_by_pollutant)

0:	learn: 0.9642103	total: 4.16s	remaining: 6m 52s
10:	learn: 0.7854615	total: 45.8s	remaining: 6m 10s

In [ ]:
import shutil

shutil.make_archive("models",  "zip", "pretrained_models/")

In [ ]:
#!c1.8
metrics_df_2 = pd.concat(metrics)

In [ ]:
metrics_df_2.groupby(level=0).mean()

In [ ]:
#!c1.8
metrics_df.groupby(level=0).mean()

In [ ]:
#!c1.8
metrics_df.groupby(level=1).mean()

In [ ]:
metrics_df_2.groupby(level=1).mean()

In [ ]:
#!c1.8
metrics_df.groupby(level=2).mean()

In [ ]:
#!c1.8
metrics_df_2.groupby(level=2).mean()

In [ ]:
pd.concat(f_imp).reset_index().drop("level_2", axis=1).drop_duplicates(subset="features").sort_values("importance", ascending=False).head(40)